
var __cov_IPczKZ02MfFZnhP5ldJzcQ = (Function('return this'))();
if (!__cov_IPczKZ02MfFZnhP5ldJzcQ.__coverage__) { __cov_IPczKZ02MfFZnhP5ldJzcQ.__coverage__ = {}; }
__cov_IPczKZ02MfFZnhP5ldJzcQ = __cov_IPczKZ02MfFZnhP5ldJzcQ.__coverage__;
if (!(__cov_IPczKZ02MfFZnhP5ldJzcQ['app/js/chat/ChatController.js'])) {
   __cov_IPczKZ02MfFZnhP5ldJzcQ['app/js/chat/ChatController.js'] = {"path":"app/js/chat/ChatController.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0},"b":{},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":1,"loc":{"start":{"line":1,"column":8},"end":{"line":1,"column":29}}},"2":{"name":"(anonymous_2)","line":4,"loc":{"start":{"line":4,"column":11},"end":{"line":4,"column":58}}},"3":{"name":"(anonymous_3)","line":7,"loc":{"start":{"line":7,"column":38},"end":{"line":7,"column":59}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":13,"column":3}},"2":{"start":{"line":4,"column":4},"end":{"line":12,"column":6}},"3":{"start":{"line":5,"column":8},"end":{"line":5,"column":40}},"4":{"start":{"line":7,"column":8},"end":{"line":11,"column":11}},"5":{"start":{"line":8,"column":12},"end":{"line":8,"column":54}},"6":{"start":{"line":9,"column":12},"end":{"line":9,"column":44}},"7":{"start":{"line":10,"column":12},"end":{"line":10,"column":43}}},"branchMap":{}};
}
__cov_IPczKZ02MfFZnhP5ldJzcQ = __cov_IPczKZ02MfFZnhP5ldJzcQ['app/js/chat/ChatController.js'];
__cov_IPczKZ02MfFZnhP5ldJzcQ.s['1']++;define(function(require){'use strict';__cov_IPczKZ02MfFZnhP5ldJzcQ.f['1']++;__cov_IPczKZ02MfFZnhP5ldJzcQ.s['2']++;return function($rootScope,$scope,User,Session){__cov_IPczKZ02MfFZnhP5ldJzcQ.f['2']++;__cov_IPczKZ02MfFZnhP5ldJzcQ.s['3']++;User.get(Session.getUserId());__cov_IPczKZ02MfFZnhP5ldJzcQ.s['4']++;$scope.$on('USER_RETRIEVED',function(e,user){__cov_IPczKZ02MfFZnhP5ldJzcQ.f['3']++;__cov_IPczKZ02MfFZnhP5ldJzcQ.s['5']++;$('#user-menu').removeClass('hidden');__cov_IPczKZ02MfFZnhP5ldJzcQ.s['6']++;$rootScope.user=user.name;__cov_IPczKZ02MfFZnhP5ldJzcQ.s['7']++;$rootScope.user_id=user._id;});};});
