
var __cov_IiKJb75vwqYiwjE6kUrHZQ = (Function('return this'))();
if (!__cov_IiKJb75vwqYiwjE6kUrHZQ.__coverage__) { __cov_IiKJb75vwqYiwjE6kUrHZQ.__coverage__ = {}; }
__cov_IiKJb75vwqYiwjE6kUrHZQ = __cov_IiKJb75vwqYiwjE6kUrHZQ.__coverage__;
if (!(__cov_IiKJb75vwqYiwjE6kUrHZQ['app/js/chat/ChatModule.js'])) {
   __cov_IiKJb75vwqYiwjE6kUrHZQ['app/js/chat/ChatModule.js'] = {"path":"app/js/chat/ChatModule.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0},"b":{},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":1,"loc":{"start":{"line":1,"column":8},"end":{"line":1,"column":29}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":24,"column":3}},"2":{"start":{"line":4,"column":4},"end":{"line":4,"column":59}},"3":{"start":{"line":5,"column":4},"end":{"line":5,"column":59}},"4":{"start":{"line":6,"column":4},"end":{"line":6,"column":56}},"5":{"start":{"line":7,"column":4},"end":{"line":7,"column":53}},"6":{"start":{"line":8,"column":4},"end":{"line":8,"column":55}},"7":{"start":{"line":9,"column":4},"end":{"line":9,"column":56}},"8":{"start":{"line":11,"column":4},"end":{"line":11,"column":60}},"9":{"start":{"line":13,"column":4},"end":{"line":13,"column":72}},"10":{"start":{"line":15,"column":4},"end":{"line":15,"column":120}},"11":{"start":{"line":17,"column":4},"end":{"line":17,"column":166}},"12":{"start":{"line":19,"column":4},"end":{"line":19,"column":126}},"13":{"start":{"line":21,"column":4},"end":{"line":21,"column":56}},"14":{"start":{"line":23,"column":4},"end":{"line":23,"column":56}}},"branchMap":{}};
}
__cov_IiKJb75vwqYiwjE6kUrHZQ = __cov_IiKJb75vwqYiwjE6kUrHZQ['app/js/chat/ChatModule.js'];
__cov_IiKJb75vwqYiwjE6kUrHZQ.s['1']++;define(function(require){'use strict';__cov_IiKJb75vwqYiwjE6kUrHZQ.f['1']++;__cov_IiKJb75vwqYiwjE6kUrHZQ.s['2']++;var ChatController=require('chat/ChatController');__cov_IiKJb75vwqYiwjE6kUrHZQ.s['3']++;var ChatDateFilter=require('chat/ChatDateFilter');__cov_IiKJb75vwqYiwjE6kUrHZQ.s['4']++;var ChatDetails=require('chat/ChatDetails');__cov_IiKJb75vwqYiwjE6kUrHZQ.s['5']++;var ChatList=require('chat/ChatList');__cov_IiKJb75vwqYiwjE6kUrHZQ.s['6']++;var ChatRouter=require('chat/ChatRouter');__cov_IiKJb75vwqYiwjE6kUrHZQ.s['7']++;var ChatService=require('chat/ChatService');__cov_IiKJb75vwqYiwjE6kUrHZQ.s['8']++;var ChatModule=angular.module('ChatModule',[]);__cov_IiKJb75vwqYiwjE6kUrHZQ.s['9']++;ChatModule.factory('ChatService',['BaseService',ChatService]);__cov_IiKJb75vwqYiwjE6kUrHZQ.s['10']++;ChatModule.controller('ChatBaseCtrl',['$rootScope','$scope','UserService','SessionService',ChatController]);__cov_IiKJb75vwqYiwjE6kUrHZQ.s['11']++;ChatModule.controller('ChatDetailsCtrl',['$scope','$stateParams','config','ChatService','MessageService','SessionService','SignService',ChatDetails]);__cov_IiKJb75vwqYiwjE6kUrHZQ.s['12']++;ChatModule.controller('ChatListCtrl',['$scope','$state','ChatService','SessionService','UserService',ChatList]);__cov_IiKJb75vwqYiwjE6kUrHZQ.s['13']++;ChatModule.filter('chatDate',[ChatDateFilter]);__cov_IiKJb75vwqYiwjE6kUrHZQ.s['14']++;ChatModule.config(['$stateProvider',ChatRouter]);});
