
var __cov_xEeuSmB80AypuJxe9Bdlag = (Function('return this'))();
if (!__cov_xEeuSmB80AypuJxe9Bdlag.__coverage__) { __cov_xEeuSmB80AypuJxe9Bdlag.__coverage__ = {}; }
__cov_xEeuSmB80AypuJxe9Bdlag = __cov_xEeuSmB80AypuJxe9Bdlag.__coverage__;
if (!(__cov_xEeuSmB80AypuJxe9Bdlag['app/js/session/EndController.js'])) {
   __cov_xEeuSmB80AypuJxe9Bdlag['app/js/session/EndController.js'] = {"path":"app/js/session/EndController.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0},"b":{"1":[0,0]},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":1,"loc":{"start":{"line":1,"column":8},"end":{"line":1,"column":29}}},"2":{"name":"(anonymous_2)","line":4,"loc":{"start":{"line":4,"column":11},"end":{"line":4,"column":59}}},"3":{"name":"(anonymous_3)","line":6,"loc":{"start":{"line":6,"column":38},"end":{"line":6,"column":49}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":14,"column":3}},"2":{"start":{"line":4,"column":4},"end":{"line":13,"column":6}},"3":{"start":{"line":5,"column":8},"end":{"line":5,"column":28}},"4":{"start":{"line":6,"column":8},"end":{"line":12,"column":11}},"5":{"start":{"line":7,"column":12},"end":{"line":9,"column":13}},"6":{"start":{"line":8,"column":16},"end":{"line":8,"column":36}},"7":{"start":{"line":11,"column":12},"end":{"line":11,"column":39}}},"branchMap":{"1":{"line":7,"type":"if","locations":[{"start":{"line":7,"column":12},"end":{"line":7,"column":12}},{"start":{"line":7,"column":12},"end":{"line":7,"column":12}}]}}};
}
__cov_xEeuSmB80AypuJxe9Bdlag = __cov_xEeuSmB80AypuJxe9Bdlag['app/js/session/EndController.js'];
__cov_xEeuSmB80AypuJxe9Bdlag.s['1']++;define(function(require){'use strict';__cov_xEeuSmB80AypuJxe9Bdlag.f['1']++;__cov_xEeuSmB80AypuJxe9Bdlag.s['2']++;return function($scope,$location,socket,Session){__cov_xEeuSmB80AypuJxe9Bdlag.f['2']++;__cov_xEeuSmB80AypuJxe9Bdlag.s['3']++;Session.terminate();__cov_xEeuSmB80AypuJxe9Bdlag.s['4']++;$scope.$on('LOGOUT_SUCCESS',function(){__cov_xEeuSmB80AypuJxe9Bdlag.f['3']++;__cov_xEeuSmB80AypuJxe9Bdlag.s['5']++;if(socket.isConnected()){__cov_xEeuSmB80AypuJxe9Bdlag.b['1'][0]++;__cov_xEeuSmB80AypuJxe9Bdlag.s['6']++;socket.disconnect();}else{__cov_xEeuSmB80AypuJxe9Bdlag.b['1'][1]++;}__cov_xEeuSmB80AypuJxe9Bdlag.s['7']++;$location.path('/login');});};});
