
var __cov_B8$ZGaiWQVvwEC6oTeWxHQ = (Function('return this'))();
if (!__cov_B8$ZGaiWQVvwEC6oTeWxHQ.__coverage__) { __cov_B8$ZGaiWQVvwEC6oTeWxHQ.__coverage__ = {}; }
__cov_B8$ZGaiWQVvwEC6oTeWxHQ = __cov_B8$ZGaiWQVvwEC6oTeWxHQ.__coverage__;
if (!(__cov_B8$ZGaiWQVvwEC6oTeWxHQ['app/js/session/SessionModule.js'])) {
   __cov_B8$ZGaiWQVvwEC6oTeWxHQ['app/js/session/SessionModule.js'] = {"path":"app/js/session/SessionModule.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0},"b":{},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":1,"loc":{"start":{"line":1,"column":8},"end":{"line":1,"column":29}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":18,"column":3}},"2":{"start":{"line":4,"column":4},"end":{"line":4,"column":65}},"3":{"start":{"line":5,"column":4},"end":{"line":5,"column":65}},"4":{"start":{"line":6,"column":4},"end":{"line":6,"column":66}},"5":{"start":{"line":7,"column":4},"end":{"line":7,"column":67}},"6":{"start":{"line":9,"column":4},"end":{"line":9,"column":67}},"7":{"start":{"line":11,"column":4},"end":{"line":11,"column":114}},"8":{"start":{"line":13,"column":4},"end":{"line":13,"column":137}},"9":{"start":{"line":15,"column":4},"end":{"line":15,"column":119}},"10":{"start":{"line":17,"column":4},"end":{"line":17,"column":62}}},"branchMap":{}};
}
__cov_B8$ZGaiWQVvwEC6oTeWxHQ = __cov_B8$ZGaiWQVvwEC6oTeWxHQ['app/js/session/SessionModule.js'];
__cov_B8$ZGaiWQVvwEC6oTeWxHQ.s['1']++;define(function(require){'use strict';__cov_B8$ZGaiWQVvwEC6oTeWxHQ.f['1']++;__cov_B8$ZGaiWQVvwEC6oTeWxHQ.s['2']++;var EndController=require('session/EndController');__cov_B8$ZGaiWQVvwEC6oTeWxHQ.s['3']++;var SessionRouter=require('session/SessionRouter');__cov_B8$ZGaiWQVvwEC6oTeWxHQ.s['4']++;var SessionService=require('session/SessionService');__cov_B8$ZGaiWQVvwEC6oTeWxHQ.s['5']++;var StartController=require('session/StartController');__cov_B8$ZGaiWQVvwEC6oTeWxHQ.s['6']++;var SessionModule=angular.module('SessionModule',[]);__cov_B8$ZGaiWQVvwEC6oTeWxHQ.s['7']++;SessionModule.factory('SessionService',['$rootScope','$cookies','$resource','config',SessionService]);__cov_B8$ZGaiWQVvwEC6oTeWxHQ.s['8']++;SessionModule.controller('SessionStartCtrl',['$rootScope','$scope','$location','socket','SessionService',StartController]);__cov_B8$ZGaiWQVvwEC6oTeWxHQ.s['9']++;SessionModule.controller('SessionEndCtrl',['$scope','$location','socket','SessionService',EndController]);__cov_B8$ZGaiWQVvwEC6oTeWxHQ.s['10']++;SessionModule.config(['$stateProvider',SessionRouter]);});
