
var __cov_HSw2mwIKSmV0CQnjBn0Nzg = (Function('return this'))();
if (!__cov_HSw2mwIKSmV0CQnjBn0Nzg.__coverage__) { __cov_HSw2mwIKSmV0CQnjBn0Nzg.__coverage__ = {}; }
__cov_HSw2mwIKSmV0CQnjBn0Nzg = __cov_HSw2mwIKSmV0CQnjBn0Nzg.__coverage__;
if (!(__cov_HSw2mwIKSmV0CQnjBn0Nzg['app/js/user/RemoveController.js'])) {
   __cov_HSw2mwIKSmV0CQnjBn0Nzg['app/js/user/RemoveController.js'] = {"path":"app/js/user/RemoveController.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"b":{"1":[0,0]},"f":{"1":0,"2":0,"3":0,"4":0},"fnMap":{"1":{"name":"(anonymous_1)","line":1,"loc":{"start":{"line":1,"column":8},"end":{"line":1,"column":29}}},"2":{"name":"(anonymous_2)","line":4,"loc":{"start":{"line":4,"column":11},"end":{"line":4,"column":79}}},"3":{"name":"(anonymous_3)","line":7,"loc":{"start":{"line":7,"column":36},"end":{"line":7,"column":48}}},"4":{"name":"(anonymous_4)","line":10,"loc":{"start":{"line":10,"column":38},"end":{"line":10,"column":50}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":18,"column":3}},"2":{"start":{"line":4,"column":4},"end":{"line":17,"column":6}},"3":{"start":{"line":5,"column":8},"end":{"line":5,"column":39}},"4":{"start":{"line":7,"column":8},"end":{"line":9,"column":11}},"5":{"start":{"line":8,"column":12},"end":{"line":8,"column":32}},"6":{"start":{"line":10,"column":8},"end":{"line":16,"column":11}},"7":{"start":{"line":11,"column":12},"end":{"line":13,"column":13}},"8":{"start":{"line":12,"column":16},"end":{"line":12,"column":36}},"9":{"start":{"line":15,"column":12},"end":{"line":15,"column":39}}},"branchMap":{"1":{"line":11,"type":"if","locations":[{"start":{"line":11,"column":12},"end":{"line":11,"column":12}},{"start":{"line":11,"column":12},"end":{"line":11,"column":12}}]}}};
}
__cov_HSw2mwIKSmV0CQnjBn0Nzg = __cov_HSw2mwIKSmV0CQnjBn0Nzg['app/js/user/RemoveController.js'];
__cov_HSw2mwIKSmV0CQnjBn0Nzg.s['1']++;define(function(require){'use strict';__cov_HSw2mwIKSmV0CQnjBn0Nzg.f['1']++;__cov_HSw2mwIKSmV0CQnjBn0Nzg.s['2']++;return function($scope,$location,$stateParams,socket,User,Session){__cov_HSw2mwIKSmV0CQnjBn0Nzg.f['2']++;__cov_HSw2mwIKSmV0CQnjBn0Nzg.s['3']++;User.remove($stateParams.id);__cov_HSw2mwIKSmV0CQnjBn0Nzg.s['4']++;$scope.$on('USER_REMOVED',function(){__cov_HSw2mwIKSmV0CQnjBn0Nzg.f['3']++;__cov_HSw2mwIKSmV0CQnjBn0Nzg.s['5']++;Session.terminate();});__cov_HSw2mwIKSmV0CQnjBn0Nzg.s['6']++;$scope.$on('LOGOUT_SUCCESS',function(){__cov_HSw2mwIKSmV0CQnjBn0Nzg.f['4']++;__cov_HSw2mwIKSmV0CQnjBn0Nzg.s['7']++;if(socket.isConnected()){__cov_HSw2mwIKSmV0CQnjBn0Nzg.b['1'][0]++;__cov_HSw2mwIKSmV0CQnjBn0Nzg.s['8']++;socket.disconnect();}else{__cov_HSw2mwIKSmV0CQnjBn0Nzg.b['1'][1]++;}__cov_HSw2mwIKSmV0CQnjBn0Nzg.s['9']++;$location.path('/login');});};});
