
var __cov_tZwOrJeLHZsVF4MYjiPF1w = (Function('return this'))();
if (!__cov_tZwOrJeLHZsVF4MYjiPF1w.__coverage__) { __cov_tZwOrJeLHZsVF4MYjiPF1w.__coverage__ = {}; }
__cov_tZwOrJeLHZsVF4MYjiPF1w = __cov_tZwOrJeLHZsVF4MYjiPF1w.__coverage__;
if (!(__cov_tZwOrJeLHZsVF4MYjiPF1w['app/js/user/UserModule.js'])) {
   __cov_tZwOrJeLHZsVF4MYjiPF1w['app/js/user/UserModule.js'] = {"path":"app/js/user/UserModule.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0},"b":{},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":1,"loc":{"start":{"line":1,"column":8},"end":{"line":1,"column":29}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":18,"column":3}},"2":{"start":{"line":4,"column":4},"end":{"line":4,"column":67}},"3":{"start":{"line":5,"column":4},"end":{"line":5,"column":65}},"4":{"start":{"line":6,"column":4},"end":{"line":6,"column":59}},"5":{"start":{"line":7,"column":4},"end":{"line":7,"column":60}},"6":{"start":{"line":9,"column":4},"end":{"line":9,"column":64}},"7":{"start":{"line":11,"column":4},"end":{"line":11,"column":72}},"8":{"start":{"line":13,"column":4},"end":{"line":13,"column":110}},"9":{"start":{"line":15,"column":4},"end":{"line":15,"column":150}},"10":{"start":{"line":17,"column":4},"end":{"line":17,"column":58}}},"branchMap":{}};
}
__cov_tZwOrJeLHZsVF4MYjiPF1w = __cov_tZwOrJeLHZsVF4MYjiPF1w['app/js/user/UserModule.js'];
__cov_tZwOrJeLHZsVF4MYjiPF1w.s['1']++;define(function(require){'use strict';__cov_tZwOrJeLHZsVF4MYjiPF1w.f['1']++;__cov_tZwOrJeLHZsVF4MYjiPF1w.s['2']++;var RegisterController=require('user/RegisterController');__cov_tZwOrJeLHZsVF4MYjiPF1w.s['3']++;var RemoveController=require('user/RemoveController');__cov_tZwOrJeLHZsVF4MYjiPF1w.s['4']++;var UserRouter=require('user/UserRouter');__cov_tZwOrJeLHZsVF4MYjiPF1w.s['5']++;var UserService=require('user/UserService');__cov_tZwOrJeLHZsVF4MYjiPF1w.s['6']++;var UserModule=angular.module('UserModule',[]);__cov_tZwOrJeLHZsVF4MYjiPF1w.s['7']++;UserModule.factory('UserService',['BaseService',UserService]);__cov_tZwOrJeLHZsVF4MYjiPF1w.s['8']++;UserModule.controller('UserRegisterCtrl',['$scope','$location','UserService',RegisterController]);__cov_tZwOrJeLHZsVF4MYjiPF1w.s['9']++;UserModule.controller('UserRemoveCtrl',['$scope','$location','$stateParams','socket','UserService','SessionService',RemoveController]);__cov_tZwOrJeLHZsVF4MYjiPF1w.s['10']++;UserModule.config(['$stateProvider',UserRouter]);});
