
var __cov_I4mPjWHnNEmt4DdVKCLcsw = (Function('return this'))();
if (!__cov_I4mPjWHnNEmt4DdVKCLcsw.__coverage__) { __cov_I4mPjWHnNEmt4DdVKCLcsw.__coverage__ = {}; }
__cov_I4mPjWHnNEmt4DdVKCLcsw = __cov_I4mPjWHnNEmt4DdVKCLcsw.__coverage__;
if (!(__cov_I4mPjWHnNEmt4DdVKCLcsw['app/js/user/UserService.js'])) {
   __cov_I4mPjWHnNEmt4DdVKCLcsw['app/js/user/UserService.js'] = {"path":"app/js/user/UserService.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0},"b":{},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":1,"loc":{"start":{"line":1,"column":8},"end":{"line":1,"column":29}}},"2":{"name":"(anonymous_2)","line":4,"loc":{"start":{"line":4,"column":11},"end":{"line":4,"column":36}}},"3":{"name":"(anonymous_3)","line":7,"loc":{"start":{"line":7,"column":30},"end":{"line":7,"column":48}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":14,"column":3}},"2":{"start":{"line":4,"column":4},"end":{"line":13,"column":6}},"3":{"start":{"line":5,"column":8},"end":{"line":5,"column":65}},"4":{"start":{"line":7,"column":8},"end":{"line":10,"column":10}},"5":{"start":{"line":8,"column":12},"end":{"line":8,"column":36}},"6":{"start":{"line":9,"column":12},"end":{"line":9,"column":65}},"7":{"start":{"line":12,"column":8},"end":{"line":12,"column":27}}},"branchMap":{}};
}
__cov_I4mPjWHnNEmt4DdVKCLcsw = __cov_I4mPjWHnNEmt4DdVKCLcsw['app/js/user/UserService.js'];
__cov_I4mPjWHnNEmt4DdVKCLcsw.s['1']++;define(function(require){'use strict';__cov_I4mPjWHnNEmt4DdVKCLcsw.f['1']++;__cov_I4mPjWHnNEmt4DdVKCLcsw.s['2']++;return function(BaseService){__cov_I4mPjWHnNEmt4DdVKCLcsw.f['2']++;__cov_I4mPjWHnNEmt4DdVKCLcsw.s['3']++;var UserService=new BaseService('USER','users');__cov_I4mPjWHnNEmt4DdVKCLcsw.s['4']++;UserService.create=function(user){__cov_I4mPjWHnNEmt4DdVKCLcsw.f['3']++;__cov_I4mPjWHnNEmt4DdVKCLcsw.s['5']++;user.access_level=3;__cov_I4mPjWHnNEmt4DdVKCLcsw.s['6']++;BaseService.prototype.create.apply(this,[user]);};__cov_I4mPjWHnNEmt4DdVKCLcsw.s['7']++;return UserService;};});
